name: Generate Snake Contribution Graph

on:
  schedule: # Run at 12am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Contribution Graph
        uses: Platane/snk@v2
        with:
          github_user_name: 2003atharv
          # Optionally, you can customize the output file
          output: dist/github-contribution-grid-snake.svg

      - name: Upload Snake SVG
        uses: actions/upload-artifact@v2
        with:
          name: github-contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push the Snake
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated snake contribution graph"
          git push
